---
title: "Vignette: Using the Count Regression Toolkit"
---

## Example Model

This vignette demonstrates how to use the Shiny App to fit and evaluate count regression models.

---

## Step 1: Load Data

Use the sample dataset:

**Ache Monkey (McMillan)**

Response variable:

- `Kills` (number of successful hunts)

Predictor:

- `Age`

---

## Step 2: Look at summary of data

After choosing "Poisson" as our model type and pressing **Fit Model**, the "Data Summary" tab should show:

- Mean: 2.787
- Variance: 40.171  

Clearly, the variance is much larger than the mean, which indicates overdispersion.

---

## Step 3: Check conditions and diagnostics

The "Model Conditions" and "Diagnostics" tabs show a dispersion ratio of 11.679, confirming the overdispersion, and indicating we should try an alternative model.

---

## Step 4: Try alternative

Try Negative Binomial so that we can use AIC and log-likelihood, while hopefully fixing the overdispersion issue. So fit the model again but as a Negative Binomial Regression.

---

## Step 5: New diagnostics

"Diagnostics" tab now shows an improved RQR plot and Pearson residual plot, indicating a better fit has been found. This can be confirmed with the "Model Comparison" tab, by comparing the AIC's. A Generalized Poisson model also looks appropriate, so that can be used as well.

---

## Step 6: Interpretation

From Model Output for Negative Binomial:

Holding other variables constant, a one-unit increase in Age is associated with a 5.73% increase in the expected count of kills.

From Model Output for Generalized Poisson:

Holding other variables constant, a one-unit increase in Age is associated with a 3.27% increase in the expected count of kills.

This interpretation is based on the exponentiated predictor coefficient.